[[minio]]
arch = "aarch64"
git-tree-sha1 = "ad524c95907ec56a0325220d11b60536ce0047f5"
os = "macos"

    [[minio.download]]
    sha256 = "6f1c65ceeed72ffe4790f4e97ced65f26d62eb1f4aabce8ed002d362db18e438"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+1/minio.v1.0.0.aarch64-apple-darwin.tar.gz"
[[minio]]
arch = "aarch64"
git-tree-sha1 = "cd281501b88180d28ecdaad51744028a80325ebb"
libc = "glibc"
os = "linux"

    [[minio.download]]
    sha256 = "428c9e97454776b35b7dbebcf3f54957ae77c8b66ae1a6397ee56f8f821af134"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+1/minio.v1.0.0.aarch64-linux-gnu.tar.gz"
[[minio]]
arch = "aarch64"
git-tree-sha1 = "b134c079c0fbb2c75b8d618bb6cb197483424990"
libc = "musl"
os = "linux"

    [[minio.download]]
    sha256 = "ad9cf90ccdb4d3a78cd790536e7b69cec0aae8cdc0c1ef1541edaf6adb77a44b"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+1/minio.v1.0.0.aarch64-linux-musl.tar.gz"
[[minio]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1d836fb2e0ac4751acc9c1f60ffc2ffc9cbb6733"
libc = "glibc"
os = "linux"

    [[minio.download]]
    sha256 = "3b0416124520db85ff471d3f840cc99e128e3b16091d22890760c2693df8b937"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+1/minio.v1.0.0.armv6l-linux-gnueabihf.tar.gz"
[[minio]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a30265687cb16fed4a6ad83bd45aa5910c12b206"
libc = "musl"
os = "linux"

    [[minio.download]]
    sha256 = "bc560744e51d46e2d04affed7dcabac269c950c0c6564e4bdf501313c408773e"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+1/minio.v1.0.0.armv6l-linux-musleabihf.tar.gz"
[[minio]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "837ecd14e3fe7381354707b74f49fdc1500ee8fb"
libc = "glibc"
os = "linux"

    [[minio.download]]
    sha256 = "246f8ab881e32a3660b550bbf96ec38b411b8dc43ebe713e1a17cddac43979a3"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+1/minio.v1.0.0.armv7l-linux-gnueabihf.tar.gz"
[[minio]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eda6dd25a4f5b8adb1f4896ec11fa69ea0c1286b"
libc = "musl"
os = "linux"

    [[minio.download]]
    sha256 = "a8e1ce4e6ff672b219a6e2dcd13e3def32bb68005b6c560ec08f8c3be8b55c4f"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+1/minio.v1.0.0.armv7l-linux-musleabihf.tar.gz"
[[minio]]
arch = "i686"
git-tree-sha1 = "281a281c451bb02d90c76a64e18ac5195f445bf0"
libc = "glibc"
os = "linux"

    [[minio.download]]
    sha256 = "d0a1c1ef376c026cd0141d1f594236e33af9e3ff5ecec84186a3511f0db1d71a"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+1/minio.v1.0.0.i686-linux-gnu.tar.gz"
[[minio]]
arch = "i686"
git-tree-sha1 = "f96f011304d68df8ff654fc535e3f9a9722e458f"
libc = "musl"
os = "linux"

    [[minio.download]]
    sha256 = "2cb7c4f4216c0c2fea35a22ce601d8f04bc0de892c1c0647b6c7049e46f3da36"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+1/minio.v1.0.0.i686-linux-musl.tar.gz"
[[minio]]
arch = "i686"
git-tree-sha1 = "fd544fc51225a94364f396634be98f324de61be2"
os = "windows"

    [[minio.download]]
    sha256 = "34ddc6f71fbb9dc0e7ed8660720804ea3401a1ec6f1db7ae02ba2da78874512a"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+1/minio.v1.0.0.i686-w64-mingw32.tar.gz"
[[minio]]
arch = "powerpc64le"
git-tree-sha1 = "4a7032a47e5e260c744f258ec30b435e27862e42"
libc = "glibc"
os = "linux"

    [[minio.download]]
    sha256 = "c64eca2a934aa4eca7e611aa866d9d46b4102bb66139415a4dcff1d1be101331"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+1/minio.v1.0.0.powerpc64le-linux-gnu.tar.gz"
[[minio]]
arch = "x86_64"
git-tree-sha1 = "a355cc1d8a2b29f5963180f1ebce5c1216593dea"
os = "macos"

    [[minio.download]]
    sha256 = "0e2399c13c08c3040102f4495e526c7914b6242bb92d25ae53f56e6be29565e7"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+1/minio.v1.0.0.x86_64-apple-darwin.tar.gz"
[[minio]]
arch = "x86_64"
git-tree-sha1 = "4af9de354b1d02264523f343e27c7b2fd76b2daa"
libc = "glibc"
os = "linux"

    [[minio.download]]
    sha256 = "ee4ce56c4e3b3eede4d804ec5ccc5fa2336101e6ddb025a9a6627b0829c9e39b"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+1/minio.v1.0.0.x86_64-linux-gnu.tar.gz"
[[minio]]
arch = "x86_64"
git-tree-sha1 = "607e46d04b69b3e225051e80e6d41a17b9c0b0b8"
libc = "musl"
os = "linux"

    [[minio.download]]
    sha256 = "a94ad25aa9eea028b06f86578b19c856a5729c0e4928e59b57705959144ef29f"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+1/minio.v1.0.0.x86_64-linux-musl.tar.gz"
[[minio]]
arch = "x86_64"
git-tree-sha1 = "8dc336ff0459207033754aef993e020192549a04"
os = "freebsd"

    [[minio.download]]
    sha256 = "02c2f9111ad0ff5ccc5c9730a108081df4a505c319d88a09302a117ba6bf3925"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+1/minio.v1.0.0.x86_64-unknown-freebsd.tar.gz"
[[minio]]
arch = "x86_64"
git-tree-sha1 = "a9c487fe62d20af6cfd565fc98b55d726c77be42"
os = "windows"

    [[minio.download]]
    sha256 = "8f4e1090282ee4ca932ac264854e19a655089170e1dca695ef0c6cd3ddd950be"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+1/minio.v1.0.0.x86_64-w64-mingw32.tar.gz"
