[[minio]]
arch = "aarch64"
git-tree-sha1 = "4d9b014d4d57ad2474f61081910c28d6384726a4"
os = "macos"

    [[minio.download]]
    sha256 = "6eebbbaaffb6d3a3ee5ccf685f3f26b468d90a01fed60b7b90c2ed7a7637eb3c"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+0/minio.v1.0.0.aarch64-apple-darwin.tar.gz"
[[minio]]
arch = "aarch64"
git-tree-sha1 = "5a07c5b03cdd045966d3bd4a3818a1b60dbf2b07"
libc = "glibc"
os = "linux"

    [[minio.download]]
    sha256 = "727d9a6909dac02271ba4fa500656fc42b1d82b2968bc6a0843175be2ed6543e"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+0/minio.v1.0.0.aarch64-linux-gnu.tar.gz"
[[minio]]
arch = "aarch64"
git-tree-sha1 = "a45e56c8ea20d3356cd9716d0bbb174d16d6088a"
libc = "musl"
os = "linux"

    [[minio.download]]
    sha256 = "820e45ef65a79572f4bbc17ecd3eb629c37b89387b2bfe702b11a999091b8089"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+0/minio.v1.0.0.aarch64-linux-musl.tar.gz"
[[minio]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4e6695eddd13dd2b969ac8d11243401428905a8e"
libc = "glibc"
os = "linux"

    [[minio.download]]
    sha256 = "ffd3d0f6fdfdffb288ca096ad9da236cfcbe751d1d21bf9a9ab36a2e67e05985"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+0/minio.v1.0.0.armv6l-linux-gnueabihf.tar.gz"
[[minio]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a35379546675c355017fd5d92e26a1da06bb7b99"
libc = "musl"
os = "linux"

    [[minio.download]]
    sha256 = "1a7867e83aba15f3f283f5505191f4d0d8c4560c9e83f78cf0ee0ca4e3ab7cbb"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+0/minio.v1.0.0.armv6l-linux-musleabihf.tar.gz"
[[minio]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2b28d5034b9d6f98115e42060cf94a912657e344"
libc = "glibc"
os = "linux"

    [[minio.download]]
    sha256 = "40f437f29dd415d0188482fba08588a396115f3ed2714100223d30f00208545c"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+0/minio.v1.0.0.armv7l-linux-gnueabihf.tar.gz"
[[minio]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "41340573c6d5857fc6957954c4da3963d043aea6"
libc = "musl"
os = "linux"

    [[minio.download]]
    sha256 = "106915d2070ed0831c74ddcf4ce5fbab1b32c54d21c4cc7deb15973acf32a4af"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+0/minio.v1.0.0.armv7l-linux-musleabihf.tar.gz"
[[minio]]
arch = "i686"
git-tree-sha1 = "acf20fa1c97ccb2103bf6a0237a97489a8db9002"
libc = "glibc"
os = "linux"

    [[minio.download]]
    sha256 = "4af4baaa0484d08fd2186c1871ea96b9b74e10db863abd57df825af4169c1df3"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+0/minio.v1.0.0.i686-linux-gnu.tar.gz"
[[minio]]
arch = "i686"
git-tree-sha1 = "c34cd1ee30117a1af443491f66db781256df3582"
libc = "musl"
os = "linux"

    [[minio.download]]
    sha256 = "37c981f65cfde0514e31fc9666d7a3cb43bf25444f1803245a1d5678cf8e207a"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+0/minio.v1.0.0.i686-linux-musl.tar.gz"
[[minio]]
arch = "i686"
git-tree-sha1 = "3ce8f8b5beaca363c1ea01bf0c7aca0e92ff8043"
os = "windows"

    [[minio.download]]
    sha256 = "32308d42ad53ebdc5a8cf557662cce26e819b73d71acd949b431ec532028431c"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+0/minio.v1.0.0.i686-w64-mingw32.tar.gz"
[[minio]]
arch = "powerpc64le"
git-tree-sha1 = "578a3457fb45bf0fea8cb939f5ea97a5cb2a166a"
libc = "glibc"
os = "linux"

    [[minio.download]]
    sha256 = "059fa03f468a48467dbb12327b52145c6e3bd8a28e8da107c368eaf77bf26d75"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+0/minio.v1.0.0.powerpc64le-linux-gnu.tar.gz"
[[minio]]
arch = "x86_64"
git-tree-sha1 = "880fd4f8e8fa76324b83866f25a5ef711520e453"
os = "macos"

    [[minio.download]]
    sha256 = "3020b01305e935b515ec613da8508f70c642b5d11c9455fce6f60104e784a418"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+0/minio.v1.0.0.x86_64-apple-darwin.tar.gz"
[[minio]]
arch = "x86_64"
git-tree-sha1 = "65dbc251fba52c1d0bf1f2d79e41066579740209"
libc = "glibc"
os = "linux"

    [[minio.download]]
    sha256 = "962dfa7d7038b000c483faf80b0170ad583c979e5f062c92c20d95fe5b355b95"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+0/minio.v1.0.0.x86_64-linux-gnu.tar.gz"
[[minio]]
arch = "x86_64"
git-tree-sha1 = "ae5f296f6a76cff8a26ca7a4657fdde7d387f569"
libc = "musl"
os = "linux"

    [[minio.download]]
    sha256 = "86c27a21d34f9c16991db73431104b3b5a08d6ff4fc7afb8710cf1a860a2f475"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+0/minio.v1.0.0.x86_64-linux-musl.tar.gz"
[[minio]]
arch = "x86_64"
git-tree-sha1 = "d702b5c64145cb9fbd6caf450f1842cf174ddd45"
os = "freebsd"

    [[minio.download]]
    sha256 = "79026e43e376866816cb60201811b7e0d3f8f0ac301cab500c1a054d7211ee78"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+0/minio.v1.0.0.x86_64-unknown-freebsd.tar.gz"
[[minio]]
arch = "x86_64"
git-tree-sha1 = "7624a6e7d731b11ce8f220a53069071aebebecf1"
os = "windows"

    [[minio.download]]
    sha256 = "9aaaf314eef092a895afce396f37e454a72061bc5644ebfee8368d1b4a306975"
    url = "https://github.com/JuliaBinaryWrappers/minio_jll.jl/releases/download/minio-v1.0.0+0/minio.v1.0.0.x86_64-w64-mingw32.tar.gz"
